name: rom-build

on: push

env:
  CC65_PATH: ${{ github.workspace }}/opt/cc65

jobs:
  rom-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache_cc65
      - name: Run build script
        run: bash make.bat

      - name: Upload ROM binary
        uses: actions/upload-artifact@v1
        with:
          name: fish-rom
          path: output