name: rom-build
on: push

jobs:
  rom-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
      - uses: ./.github/actions/cache_cc65
        run: bash make.bat

      - name: Upload ROM binary
        uses: actions/upload-artifact@v1
        with:
          name: fish-rom
          path: output